# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Object Recognition' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Object Recognition
  pod 'SnapKit', '~> 3.2.0'

  target 'iOS Object RecognitionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS Object RecognitionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
